const groupData = [
  {
    Group: "A-1-1-1-1",
    Campus: "Las Vegas",
    Leader: "Javier Ruiz",
    Days: "Thursday",
    Gender: "Combined",
    Marital_Status: "Married/Single",
    Demographic: ["Everyone Welcome"],
    Time: ["7:00 PM"],
    Topic: "YTH Catalog",
    InPerson: "In-Person",
  },
  {
    Group: "A-2-1-2-1",
    Campus: "Las Vegas",
    Leader: "Fernanda Ayala",
    Days: "Wednesday",
    Gender: "Female",
    Marital_Status: "Married/Single",
    Demographic: ["Gender Specific"],
    Time: ["4:00 PM"],
    Topic: "YTH Catalog",
    InPerson: "In-Person",
  },
  {
    Group: "N-1-3-2-1",
    Campus: "Las Vegas",
    Leader: "Chris Sanchez",
    Days: "Wednesday",
    Gender: "Combined",
    Marital_Status: "Married/Single",
    Demographic: ["Young Adults"],
    Time: ["6:30 PM"],
    Topic: "YTH Catalog",
    InPerson: "In-Person",
  },
  {
    Group: "N-1-4-4-1",
    Campus: "Las Vegas",
    Leader: "Dennise Castillo",
    Days: "Sunday",
    Gender: "Combined",
    Marital_Status: "Single",
    Demographic: ["Singles"],
    Time: ["12:00 PM"],
    Topic: "YTH Catalog",
    InPerson: "In-Person",
  },
  {
    Group: "R-1",
    Campus: "Las Vegas",
    Leader: "Jose Perez",
    Days: "Monday",
    Gender: "Combined",
    Marital_Status: "Single",
    Demographic: ["College"],
    Time: ["7:00 PM"],
    Topic: "YTH Catalog",
    InPerson: "In-Person",
  },
  {
    Group: "R-1-2-3-4",
    Campus: "Las Vegas",
    Leader: "Desi Ayala",
    Days: "Sunday",
    Gender: "Combined",
    Marital_Status: "Single",
    Demographic: ["College"],
    Time: ["10:00 AM"],
    Topic: "YTH Catalog",
    InPerson: "In-Person",
  },
  {
    Group: "F-1-3-3-4",
    Campus: "Las Vegas",
    Leader: "Jaime Lima",
    Days: "Thursday",
    Gender: "Combined",
    Marital_Status: "Single",
    Demographic: ["Married Couples"],
    Time: ["6:00 PM"],
    Topic: "YTH Catalog",
    InPerson: "In-Person",
  },
];

export default groupData;
